---
- hosts: localhost
  gather_facts: no

  tasks:

   - name: Get credential type object for GCE
     uri:
       url: "{{ tower_base_url }}credential_types/?name=Google+Compute+Engine"
       user: "{{ tower_user }}"
       password: "{{ tower_password }}"
       method: GET
       force_basic_auth: yes
       validate_certs: no
     register: credential_type
   - name: Debug credential type ID
     debug:
        msg:  "Credential Type is {{ credential_type.json.results.0.id }}"
   
   - name: create new Google Credentials
     tower_credential:
       name: "GCE Service Account for elk-demo"
       description: "GCE Service Account for elk-demo"
       organization: Default
       state: present
       kind: gce

       tower_host: "{{ tower_host }}"
       tower_username: "{{ tower_user }}"
       tower_password: "{{ tower_password }}"
       validate_certs: no
       inputs: "{{ lookup('file', gce_credential_file) }}"
     register: credential_create
   - name: Debug credential create 
     debug:
        msg:  |
         {{ credential_create }}
   
