---
- hosts: localhost
  gather_facts: no


  tasks:

   - name: create credentials to connect to GIT
     tower_credential:
       tower_host: "{{ tower_host }}"
       tower_username: "{{ tower_user }}"
       tower_password: "{{ tower_password }}"
       validate_certs: no
       name: SCM Credential
       organization: Default
       state: present
       kind: scm
       username: "{{ git_user }}"
       ssh_key_data: "{{ lookup('file', git_ssh_keyfile )  }}"
       ssh_key_unlock: "{{ git_ssh_keyfile_passphrase }}"

     register: credential_create
   - name: Debug credential create 
     debug:
        msg:  |
         {{ credential_create }}
   
