---
- hosts: localhost
  gather_facts: no


  tasks:

   - name: create credentials to connect to GIT
     tower_credential:
       tower_host: "{{ tower_host }}"
       tower_username: "{{ tower_user }}"
       tower_password: "{{ tower_password }}"
       validate_certs: no
       name: GitHub Credential
       organization: Default
       state: present
       kind: scm
       username: "{{ git_user }}"
       ssh_key_data: "{{ lookup('file', git_ssh_keyfile )  }}"
       ssh_key_unlock: "{{ git_ssh_keyfile_passphrase }}"

     register: credential_create_git
   - name: Debug credential create 
     debug:
        msg:  |
         {{ credential_create_git }}
   
   - name: create credentials to connect to VMs via ssh
     tower_credential:
       tower_host: "{{ tower_host }}"
       tower_username: "{{ tower_user }}"
       tower_password: "{{ tower_password }}"
       validate_certs: no
       name: VMs SSH Credential
       organization: Default
       state: present
       kind: ssh
       username: "{{ vms_user }}"
       ssh_key_data: "{{ lookup('file', vms_ssh_keyfile )  }}"
       ssh_key_unlock: "{{ vms_ssh_keyfile_passphrase }}"

     register: credential_create_vms
   - name: Debug credential create 
     debug:
        msg:  |
         {{ credential_create_vms }}
   
